csv_config:
  amount_columns:
    negative_debits: false
    single: true
  date_formats:
  - '%m/%d/%Y'
  field_mappings:
    account:
    - Account
    amount:
    - Amount
    category:
    - Category
    date:
    - Transaction Date
    - Post Date
    description:
    - Description
name: Chase Bank
pdf_config:
  date_formats:
  - '%m/%d'
  transaction_patterns:
  - (\d{2}/\d{2})\s+(.+?)\s+(\$?\s*-?\d{1,3}(?:,\d{3})*\.\d{2})
