name: Generic OFX
description: Generic configuration for OFX-based bank statements

ofx_config:
  encoding: "utf-8"
  fallback_encodings: ["latin-1", "cp1252", "iso-8859-1"]
  
  transaction_types:
    CREDIT: "credit"
    DEBIT: "debit"
    INT: "interest"
    DIV: "dividend"
    FEE: "fee"
    SRVCHG: "service_charge"
    DEP: "deposit"
    ATM: "atm"
    POS: "point_of_sale"
    XFER: "transfer"
    CHECK: "check"
    PAYMENT: "payment"
    CASH: "cash"
    DIRECTDEP: "direct_deposit"
    DIRECTDEBIT: "direct_debit"
    REPEATPMT: "recurring_payment"
    OTHER: "other"
  
  merchant_extraction:
    clean_payee_names: true
    extract_from_memo: true
    remove_transaction_ids: true
  
  data_validation:
    skip_pending_transactions: false
    required_fields: ["date", "amount"]